### ISSUE TITLE
QQuickPaintedItem file not found

### ISSUE THREAD

**Issue by Achifaifa** [Swordfish90/cool-retro-term#294]
Essentially the same as issue #248, except that this one happens in debian. 

qmake runs fine (in /usr/lib/i386-linux-gnu/qt5/bin/qmake), is make what raises the error.

```
In file included from lib/Session.cpp:44:0:
lib/TerminalDisplay.h:28:29: fatal error: QQuickPaintedItem: No such file or directory
 #include <QQuickPaintedItem>
                             ^
compilation terminated.
```

Not sure if there is a library missing in the dependencies or something.
##

**Comment by quartox** [comment]
I had this issue in ubuntu and it turned out that I was using qt4 for the first attempt to execute `qmake && make`. Using `make clean` did not fix this; I had to delete and re-clone the repo then use a direct path to the qt5 qmake (for the @Achifaifa setup the command would be `/usr/lib/i386-linux-gnu/qt5/bin/qmake && make`). Using `make clean` in the dependency directory might allow this to work without downloading the repo again.
