### ISSUE TITLE
Support for tabs and other related features

### ISSUE THREAD

**Issue by saward** [Swordfish90/cool-retro-term#30]
Hi,

Project looks great!  Very nicely done.

Would be good to have tabs, and other settings like scrollback history length.

**Comment by tebicap** [comment]
Sometimes modern features mixed with a retro look feels better than just a retro look (at least for me). I my case I'm using custom settings and I would like to have a tabs feature, but with a no-tabs aspect when there is not opened a second tab in order to keep the interface clean.
![Screenshot_20220602_213857](https://user-images.githubusercontent.com/16892278/171762646-542a9dd5-176f-4284-8f80-102ef9383f50.png)
